[package]
name = "todo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
askama_actix = "0.14"
actix-web = "4"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
serde = { version = "1.0", features = ["derive"] }